<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《天寶初，南曹小司寇舅，於我太夫人堂下，壘土爲山，一匱盈尺，以代彼朽木，承諸焚香瓷甌，甌甚安矣。旁植慈竹，蓋茲數峯，嶔岑嬋娟，宛有塵外數致。乃不知興之所至，而作是詩》的資料。
*/
$content=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"於我太夫人堂下。壘土爲山。"=>array("jyu1 ngo5 taai3 fu1 jan4 tong4 haa6, leoi5 tou2 wai4 saan1,"),
"一匱盈尺。以代彼朽木。"=>array("jat1 gwai6 jing4 cek3, ji5 doi6 bei2 nau2 muk6,"),
"承諸焚香瓷甌。甌甚安矣。"=>array("sing4 zyu1 fan4 hoeng1 ci4 au1, au1 sam6 on1 ji5."),
"旁植慈竹。蓋茲數峯。嶔岑嬋娟。"=>array("pong4 zik6 ci4 zuk1, goi3 zi1 sou3 fung1, jam1 sam4 sim4 gyun1,"),
"宛有塵外數致。乃不知興之所至。"=>array("jyun2 jau5 can4 ngoi6 sou3 zi3. naai5 bat1 zi1 hing3 zi1 so2 zi3,"),
"一匱功盈尺。三峯意出羣。"=>array("jat1 gwai6 gung1 jing4 cek3, saam1 fung1 ji3 ceot1 kwan4","仄仄平平仄，平平仄仄平"),
"望中疑在野。幽處欲生雲。"=>array("mong6 zung1 ji4 zoi6 je5, jau1 cyu3 juk6 sang wan4","仄平平仄仄，仄仄仄平平"),
"慈竹春陰覆。香爐曉勢分。"=>array("ci4 zuk1 ceon1 jam1 fuk1, hoeng1 lou4 hiu2 sai3 fan1","平仄平平仄，平平仄仄平"),),
"字音"=>array(
"於"=>array("jyu1"),
"我"=>array("ngo5"),
"太"=>array("taai3"),
"夫"=>array("fu1"),
"人"=>array("jan4"),
"堂"=>array("tong4"),
"下"=>array("haa6"),
"壘"=>array("leoi5"),
"土"=>array("tou2"),
"爲"=>array("wai4"),
"山"=>array("saan1"),
"一"=>array("jat1"),
"匱"=>array("gwai6"),
"盈"=>array("jing4"),
"尺"=>array("cek3"),
"以"=>array("ji5"),
"代"=>array("doi6"),
"彼"=>array("bei2"),
"朽"=>array("nau2"),
"木"=>array("muk6"),
"承"=>array("sing4"),
"諸"=>array("zyu1"),
"焚"=>array("fan4"),
"香"=>array("hoeng1"),
"瓷"=>array("ci4"),
"甌"=>array("au1"),
"甚"=>array("sam6"),
"安"=>array("on1"),
"矣"=>array("ji5."),
"旁"=>array("pong4"),
"植"=>array("zik6"),
"慈"=>array("ci4"),
"竹"=>array("zuk1"),
"蓋"=>array("goi3"),
"茲"=>array("zi1"),
"數"=>array("sou3"),
"峯"=>array("fung1"),
"嶔"=>array("jam1"),
"岑"=>array("sam4"),
"嬋"=>array("sim4"),
"娟"=>array("gyun1"),
"宛"=>array("jyun2"),
"有"=>array("jau5"),
"塵"=>array("can4"),
"外"=>array("ngoi6"),
"致"=>array("zi3."),
"乃"=>array("naai5"),
"不"=>array("bat1"),
"知"=>array("zi1"),
"興"=>array("hing3"),
"之"=>array("zi1"),
"所"=>array("so2"),
"至"=>array("zi3"),
"功"=>array("gung1"),
"三"=>array("saam1"),
"意"=>array("ji3"),
"出"=>array("ceot1"),
"羣"=>array("kwan4"),
"望"=>array("mong6"),
"中"=>array("zung1"),
"疑"=>array("ji4"),
"在"=>array("zoi6"),
"野"=>array("je5"),
"幽"=>array("jau1"),
"處"=>array("cyu3"),
"欲"=>array("juk6"),
"生"=>array("sang"),
"雲"=>array("wan4"),
"春"=>array("ceon1"),
"陰"=>array("jam1"),
"覆"=>array("fuk1"),
"爐"=>array("lou4"),
"曉"=>array("hiu2"),
"勢"=>array("sai3"),
"分"=>array("fan1")
),
"韻部"=>
array(
"〚0059:3.2.5〛"=>"羣：文韻",
"〚0059:4.2.5〛"=>"雲：文韻",
"〚0059:5.2.5〛"=>"分：文韻",
"〚0059:6.2.5〛"=>"氳：文韻")
,
"補充説明"=>
"〚3〛首聯對仗。",

);
?>