<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《李監宅二首》的資料。
*/
$粵内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"尚覺王孫貴。豪家意頗濃。"=>array("soeng6 gok3 wong4 syun1 gwai3, hou4 gaa1 ji3 po2 nung4","仄仄平平仄，平平仄仄平"),
"屛開金孔雀。褥隱繡芙蓉。"=>array("ping4 hoi1 gam1 hung2 zoek3, juk6 jan2 sau3 fu4 jung4","平平平仄仄，仄仄仄平平"),
"且食雙魚美。誰看異味重。"=>array("ce2 sik6 soeng1 jyu4 mei5, seoi4 hon1 ji6 mei6 cung4","仄仄平平仄，平平仄仄平"),
"門闌多喜色。女婿近乘龍。"=>array("mun4 laan4 do1 hei2 sik1, neoi5 sai3 gan6 sing4 lung4","平平平仄仄，仄仄仄平平"),
"華館春風起。高城煙霧開。"=>array("waa4 gun2 ceon1 fung1 hei2, gou1 sing4 jin1 mou6 hoi1","平仄平平仄，平平平仄平"),
"雜花分戶映。嬌燕入簷迴。"=>array("zaap6 faa1 fan1 wu6 jing2, giu1 jin3 jap6 jim4 wui4","仄平平仄仄，平仄仄平平"),
"一見能傾座。虛懷只愛才。"=>array("jat1 gin3 nang4 king1 zo6, heoi1 waai4 zi2 oi3 coi4","仄仄平平仄，平平仄仄平"),
"鹽車雖絆驥。名是漢庭來。"=>array("jim4 ce1 seoi1 bun6 kei3, ming4 si6 hon3 ting4 loi4","平平平仄仄，平仄仄平平"),),
"字音"=>array(
"尚"=>array("soeng6"),
"覺"=>array("gok3"),
"王"=>array("wong4"),
"孫"=>array("syun1"),
"貴"=>array("gwai3"),
"豪"=>array("hou4"),
"家"=>array("gaa1"),
"意"=>array("ji3"),
"頗"=>array("po2"),
"濃"=>array("nung4"),
"屛"=>array("ping4"),
"開"=>array("hoi1"),
"金"=>array("gam1"),
"孔"=>array("hung2"),
"雀"=>array("zoek3"),
"褥"=>array("juk6"),
"隱"=>array("jan2"),
"繡"=>array("sau3"),
"芙"=>array("fu4"),
"蓉"=>array("jung4"),
"且"=>array("ce2"),
"食"=>array("sik6"),
"雙"=>array("soeng1"),
"魚"=>array("jyu4"),
"美"=>array("mei5"),
"誰"=>array("seoi4"),
"看"=>array("hon1"),
"異"=>array("ji6"),
"味"=>array("mei6"),
"重"=>array("cung4"),
"門"=>array("mun4"),
"闌"=>array("laan4"),
"多"=>array("do1"),
"喜"=>array("hei2"),
"色"=>array("sik1"),
"女"=>array("neoi5"),
"婿"=>array("sai3"),
"近"=>array("gan6"),
"乘"=>array("sing4"),
"龍"=>array("lung4"),
"華"=>array("waa4"),
"館"=>array("gun2"),
"春"=>array("ceon1"),
"風"=>array("fung1"),
"起"=>array("hei2"),
"高"=>array("gou1"),
"城"=>array("sing4"),
"煙"=>array("jin1"),
"霧"=>array("mou6"),
"雜"=>array("zaap6"),
"花"=>array("faa1"),
"分"=>array("fan1"),
"戶"=>array("wu6"),
"映"=>array("jing2"),
"嬌"=>array("giu1"),
"燕"=>array("jin3"),
"入"=>array("jap6"),
"簷"=>array("jim4"),
"迴"=>array("wui4"),
"一"=>array("jat1"),
"見"=>array("gin3"),
"能"=>array("nang4"),
"傾"=>array("king1"),
"座"=>array("zo6"),
"虛"=>array("heoi1"),
"懷"=>array("waai4"),
"只"=>array("zi2"),
"愛"=>array("oi3"),
"才"=>array("coi4"),
"鹽"=>array("jim4"),
"車"=>array("ce1"),
"雖"=>array("seoi1"),
"絆"=>array("bun6"),
"驥"=>array("kei3"),
"名"=>array("ming4"),
"是"=>array("si6"),
"漢"=>array("hon3"),
"庭"=>array("ting4"),
"來"=>array("loi4")
),
"韻部"=>
array(
"〚0062:1:5.2.5〛"=>"濃：冬韻",
"〚0062:1:6.2.5〛"=>"蓉：冬韻",
"〚0062:1:7.2.5〛"=>"重：冬韻",
"〚0062:1:8.2.5〛"=>"龍：冬韻",
"〚0062:2:12.2.5〛"=>"開：灰韻",
"〚0062:2:13.2.5〛"=>"迴：灰韻",
"〚0062:2:14.2.5〛"=>"才：灰韻",
"〚0062:2:15.2.5〛"=>"來：灰韻")
,
"補充説明"=>
"〚1〛監，去聲。
〚2:〛首聯對仗。",

);
?>