<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《與李十二白同尋范十隱居》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"李侯有佳句。往往似陰鏗。"=>array("lei5 hau4 jau5 gaai1 geoi3, wong5 wong5 ci5 jam1 hang1","仄平仄平仄，仄仄仄平平"),
"余亦東蒙客。憐君如弟兄。"=>array("jyu4 jik6 dung1 mung4 haak3, lin4 gwan1 jyu4 dai6 hing1","平仄平平仄，平平平仄平"),
"醉眠秋共被。攜手日同行。"=>array("zeoi3 min4 cau1 gung6 pei5, kwai4 sau2 jat6 tung4 hang4","仄平平仄仄，平仄仄平平"),
"更想幽期處。還尋北郭生。"=>array("gang3 soeng2 jau1 kei4 cyu3, waan4 cam4 bak1 gwok3 sang1","仄仄平平仄，平平仄仄平"),
"入門高興發。侍立小童清。"=>array("jap6 mun4 gou1 hing3 faat3, si6 lap6 siu2 tung4 cing1","仄平平仄仄，仄仄仄平平"),
"落景聞寒杵。屯雲對古城。"=>array("lok6 jing2 man4 hon4 cyu5, tyun4 wan4 deoi3 gu2 sing4","仄仄平平仄，平平仄仄平"),
"向來吟橘頌。誰欲討蓴羹。"=>array("hoeng3 loi4 jam4 gwat1 zung6, seoi4 juk6 tou2 seon4 gang1","仄平平仄仄，平仄仄平平"),
"不願論簪笏。悠悠滄海情。"=>array("bat1 jyun6 leon4 zaam1 fat1, jau4 jau4 cong1 hoi2 cing4","仄仄平平仄，平平平仄平"),),
"字音"=>array(
"李"=>array("lei5"),
"侯"=>array("hau4"),
"有"=>array("jau5"),
"佳"=>array("gaai1"),
"句"=>array("geoi3"),
"往"=>array("wong5"),
"似"=>array("ci5"),
"陰"=>array("jam1"),
"鏗"=>array("hang1"),
"余"=>array("jyu4"),
"亦"=>array("jik6"),
"東"=>array("dung1"),
"蒙"=>array("mung4"),
"客"=>array("haak3"),
"憐"=>array("lin4"),
"君"=>array("gwan1"),
"如"=>array("jyu4"),
"弟"=>array("dai6"),
"兄"=>array("hing1"),
"醉"=>array("zeoi3"),
"眠"=>array("min4"),
"秋"=>array("cau1"),
"共"=>array("gung6"),
"被"=>array("pei5"),
"攜"=>array("kwai4"),
"手"=>array("sau2"),
"日"=>array("jat6"),
"同"=>array("tung4"),
"行"=>array("hang4"),
"更"=>array("gang3"),
"想"=>array("soeng2"),
"幽"=>array("jau1"),
"期"=>array("kei4"),
"處"=>array("cyu3"),
"還"=>array("waan4"),
"尋"=>array("cam4"),
"北"=>array("bak1"),
"郭"=>array("gwok3"),
"生"=>array("sang1"),
"入"=>array("jap6"),
"門"=>array("mun4"),
"高"=>array("gou1"),
"興"=>array("hing3"),
"發"=>array("faat3"),
"侍"=>array("si6"),
"立"=>array("lap6"),
"小"=>array("siu2"),
"童"=>array("tung4"),
"清"=>array("cing1"),
"落"=>array("lok6"),
"景"=>array("jing2"),
"聞"=>array("man4"),
"寒"=>array("hon4"),
"杵"=>array("cyu5"),
"屯"=>array("tyun4"),
"雲"=>array("wan4"),
"對"=>array("deoi3"),
"古"=>array("gu2"),
"城"=>array("sing4"),
"向"=>array("hoeng3"),
"來"=>array("loi4"),
"吟"=>array("jam4"),
"橘"=>array("gwat1"),
"頌"=>array("zung6"),
"誰"=>array("seoi4"),
"欲"=>array("juk6"),
"討"=>array("tou2"),
"蓴"=>array("seon4"),
"羹"=>array("gang1"),
"不"=>array("bat1"),
"願"=>array("jyun6"),
"論"=>array("leon4"),
"簪"=>array("zaam1"),
"笏"=>array("fat1"),
"悠"=>array("jau4"),
"滄"=>array("cong1"),
"海"=>array("hoi2"),
"情"=>array("cing4")
),
"韻部"=>
array(
"〚0095:3.2.5〛"=>"鏗：庚韻",
"〚0095:4.2.5〛"=>"兄：庚韻",
"〚0095:5.2.5〛"=>"行：庚韻",
"〚0095:6.2.5〛"=>"生：庚韻",
"〚0095:7.2.5〛"=>"清：庚韻",
"〚0095:8.2.5〛"=>"城：庚韻",
"〚0095:9.2.5〛"=>"羹：庚韻",
"〚0095:10.2.5〛"=>"情：庚韻")
,
"補充説明"=>
"〚10.1.3〛論，平聲。
此詩非五排，然句多合律，且一韻到底，故標出平仄。
〚5〛、〚8〛、〚9〛，對句。",

);
?>