<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《鄭駙馬宅宴洞中》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"主家陰洞細煙霧。留客夏簟清琅玕。"=>array("zyu2 gaa1 jam1 dung6 sai3 jin1 mou6, lau4 haak3 haa6 tim5 cing1 long4 gon1","仄平平仄仄平仄，平仄仄仄平平平"),
"春酒杯濃琥珀薄。冰漿碗碧瑪瑙寒。"=>array("ceon1 zau2 bui1 nung4 fu2 paak3 bok6, bing1 zoeng1 wun2 bik1 maa5 nou5 hon4","平仄平平仄仄仄，平平仄仄仄仄平"),
"誤疑茅堂過江麓。已入風磴霾雲端。"=>array("ng6 ji4 maau4 tong4 gwo3 gong1 luk1, ji5 jap6 fung1 dang3 maai4 wan4 dyun1","仄平平平仄平仄，仄仄平仄平平平（出句特定平仄）"),
"自是秦樓壓鄭谷。時聞雜佩聲珊珊。"=>array("zi6 si6 ceon4 lau4 aat3 zeng6 guk1, si4 man4 zaap6 pui3 seng1 saan1 saan1","仄仄平平仄仄仄，平平仄仄平平平"),),
"字音"=>array(
"主"=>array("zyu2"),
"家"=>array("gaa1"),
"陰"=>array("jam1"),
"洞"=>array("dung6"),
"細"=>array("sai3"),
"煙"=>array("jin1"),
"霧"=>array("mou6"),
"留"=>array("lau4"),
"客"=>array("haak3"),
"夏"=>array("haa6"),
"簟"=>array("tim5"),
"清"=>array("cing1"),
"琅"=>array("long4"),
"玕"=>array("gon1"),
"春"=>array("ceon1"),
"酒"=>array("zau2"),
"杯"=>array("bui1"),
"濃"=>array("nung4"),
"琥"=>array("fu2"),
"珀"=>array("paak3"),
"薄"=>array("bok6"),
"冰"=>array("bing1"),
"漿"=>array("zoeng1"),
"碗"=>array("wun2"),
"碧"=>array("bik1"),
"瑪"=>array("maa5"),
"瑙"=>array("nou5"),
"寒"=>array("hon4"),
"誤"=>array("ng6"),
"疑"=>array("ji4"),
"茅"=>array("maau4"),
"堂"=>array("tong4"),
"過"=>array("gwo3"),
"江"=>array("gong1"),
"麓"=>array("luk1"),
"已"=>array("ji5"),
"入"=>array("jap6"),
"風"=>array("fung1"),
"磴"=>array("dang3"),
"霾"=>array("maai4"),
"雲"=>array("wan4"),
"端"=>array("dyun1"),
"自"=>array("zi6"),
"是"=>array("si6"),
"秦"=>array("ceon4"),
"樓"=>array("lau4"),
"壓"=>array("aat3"),
"鄭"=>array("zeng6"),
"谷"=>array("guk1"),
"時"=>array("si4"),
"聞"=>array("man4"),
"雜"=>array("zaap6"),
"佩"=>array("pui3"),
"聲"=>array("seng1"),
"珊"=>array("saan1")
),
"韻部"=>
array(
"〚0120:3.2.7〛"=>"玕：寒韻",
"〚0120:4.2.7〛"=>"寒：寒韻",
"〚0120:5.2.7〛"=>"端：寒韻",
"〚0120:6.2.7〛"=>"珊：寒韻")
,
"補充説明"=>
"此詩多拗句。",

);
?>