<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《贈比部蕭郎中十兄》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"有美生人傑。由來積德門。"=>array("jau5 mei5 sang1 jan4 git6, jau4 loi4 zik1 dak1 mun4","仄仄平平仄，平平仄仄平"),
"漢朝丞相系。梁日帝王孫。"=>array("hon3 ciu4 sing4 soeng3 hai6, loeng4 jat6 dai3 wong4 syun1","仄平平仄仄，平仄仄平平"),
"蘊藉爲郎久。魁梧秉哲尊。"=>array("wan3 zik6 wai4 long4 gau2, fui1 ng4 bing2 zit3 zyun1","仄仄平平仄，平平仄仄平"),
"詞華傾後輩。風雅藹孤騫。"=>array("ci4 waa4 king1 hau6 bui3, fung1 ngaa5 oi2 gu1 hin1","平平平仄仄，平仄仄平平"),
"宅相榮姻戚。兒童惠討論。"=>array("zaak6 soeng3 wing4 jan1 cik1, ji4 tung4 wai6 tou2 leon4","仄仄平平仄，平平仄仄平"),
"見知眞自幼。謀拙愧諸昆。"=>array("gin3 zi1 zan1 zi6 jau3, mau4 zyut3 kwai5 zyu1 kwan1","仄平平仄仄，平仄仄平平"),
"漂蕩雲天闊。沉埋日月奔。"=>array("piu1 dong6 wan4 tin1 fut3, cam4 maai4 jat6 jyut6 ban1","平仄平平仄，平平仄仄平"),
"致君時已晚。懷古意空存。"=>array("zi3 gwan1 si4 ji5 maan5, waai4 gu2 ji3 hung1 cyun4","仄平平仄仄，平仄仄平平"),
"中散山陽鍛。愚公野谷村。"=>array("zung1 saan3 saan1 joeng4 dyun3, jyu4 gung1 je5 guk1 cyun1","平仄平平仄，平平仄仄平"),
"寧紆長者轍。歸老任乾坤。"=>array("ning4 jyu1 zoeng2 ze2 cit3, gwai1 lou5 jam6 gon1 kwan1","平平仄仄仄，平仄仄平平"),),
"字音"=>array(
"有"=>array("jau5"),
"美"=>array("mei5"),
"生"=>array("sang1"),
"人"=>array("jan4"),
"傑"=>array("git6"),
"由"=>array("jau4"),
"來"=>array("loi4"),
"積"=>array("zik1"),
"德"=>array("dak1"),
"門"=>array("mun4"),
"漢"=>array("hon3"),
"朝"=>array("ciu4"),
"丞"=>array("sing4"),
"相"=>array("soeng3"),
"系"=>array("hai6"),
"梁"=>array("loeng4"),
"日"=>array("jat6"),
"帝"=>array("dai3"),
"王"=>array("wong4"),
"孫"=>array("syun1"),
"蘊"=>array("wan3"),
"藉"=>array("zik6"),
"爲"=>array("wai4"),
"郎"=>array("long4"),
"久"=>array("gau2"),
"魁"=>array("fui1"),
"梧"=>array("ng4"),
"秉"=>array("bing2"),
"哲"=>array("zit3"),
"尊"=>array("zyun1"),
"詞"=>array("ci4"),
"華"=>array("waa4"),
"傾"=>array("king1"),
"後"=>array("hau6"),
"輩"=>array("bui3"),
"風"=>array("fung1"),
"雅"=>array("ngaa5"),
"藹"=>array("oi2"),
"孤"=>array("gu1"),
"騫"=>array("hin1"),
"宅"=>array("zaak6"),
"榮"=>array("wing4"),
"姻"=>array("jan1"),
"戚"=>array("cik1"),
"兒"=>array("ji4"),
"童"=>array("tung4"),
"惠"=>array("wai6"),
"討"=>array("tou2"),
"論"=>array("leon4"),
"見"=>array("gin3"),
"知"=>array("zi1"),
"眞"=>array("zan1"),
"自"=>array("zi6"),
"幼"=>array("jau3"),
"謀"=>array("mau4"),
"拙"=>array("zyut3"),
"愧"=>array("kwai5"),
"諸"=>array("zyu1"),
"昆"=>array("kwan1"),
"漂"=>array("piu1"),
"蕩"=>array("dong6"),
"雲"=>array("wan4"),
"天"=>array("tin1"),
"闊"=>array("fut3"),
"沉"=>array("cam4"),
"埋"=>array("maai4"),
"月"=>array("jyut6"),
"奔"=>array("ban1"),
"致"=>array("zi3"),
"君"=>array("gwan1"),
"時"=>array("si4"),
"已"=>array("ji5"),
"晚"=>array("maan5"),
"懷"=>array("waai4"),
"古"=>array("gu2"),
"意"=>array("ji3"),
"空"=>array("hung1"),
"存"=>array("cyun4"),
"中"=>array("zung1"),
"散"=>array("saan3"),
"山"=>array("saan1"),
"陽"=>array("joeng4"),
"鍛"=>array("dyun3"),
"愚"=>array("jyu4"),
"公"=>array("gung1"),
"野"=>array("je5"),
"谷"=>array("guk1"),
"村"=>array("cyun1"),
"寧"=>array("ning4"),
"紆"=>array("jyu1"),
"長"=>array("zoeng2"),
"者"=>array("ze2"),
"轍"=>array("cit3"),
"歸"=>array("gwai1"),
"老"=>array("lou5"),
"任"=>array("jam6"),
"乾"=>array("gon1"),
"坤"=>array("kwan1")
),
"韻部"=>
array(
"〚0148:3.2.5〛"=>"門：元韻",
"〚0148:4.2.5〛"=>"孫：元韻",
"〚0148:5.2.5〛"=>"尊：元韻",
"〚0148:6.2.5〛"=>"騫：先韻",
"〚0148:7.2.5〛"=>"論：元韻",
"〚0148:8.2.5〛"=>"昆：元韻",
"〚0148:9.2.5〛"=>"奔：元韻",
"〚0148:10.2.5〛"=>"存：元韻",
"〚0148:11.2.5〛"=>"村：元韻",
"〚0148:12.2.5〛"=>"坤：元韻")
,
"補充説明"=>
"〚6.2.5〛騫，唯一先韻字。",

);
?>