<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《重經昭陵》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"草昧英雄起。謳歌歷數歸。"=>array("cou2 mui6 jing1 hung4 hei2, au1 go1 lik6 sou3 gwai1","仄仄平平仄，平平仄仄平"),
"風塵三尺劍。社稷一戎衣。"=>array("fung1 can4 saam1 cek3 gim3, se5 zik1 jat1 jung4 ji1","平平平仄仄，仄仄仄平平"),
"翼亮貞文德。丕承戢武威。"=>array("jik6 loeng6 zing1 man4 dak1, pei1 sing4 cap1 mou5 wai1","仄仄平平仄，平平仄仄平"),
"聖圖天廣大。宗祀日光輝。"=>array("sing3 tou4 tin1 gwong2 daai6, zung1 zi6 jat6 gwong1 fai1","仄平平仄仄，平仄仄平平"),
"陵寢盤空曲。熊羆守翠微。"=>array("ling4 cam2 pun4 hung1 kuk1, hung4 bei1 sau2 ceoi3 mei4","平仄平平仄，平平仄仄平"),
"再窺松柏路。還見五雲飛。"=>array("zoi3 kwai1 cung4 paak3 lou6, waan4 gin3 ng5 wan4 fei1","仄平平仄仄，平仄仄平平"),),
"字音"=>array(
"草"=>array("cou2"),
"昧"=>array("mui6"),
"英"=>array("jing1"),
"雄"=>array("hung4"),
"起"=>array("hei2"),
"謳"=>array("au1"),
"歌"=>array("go1"),
"歷"=>array("lik6"),
"數"=>array("sou3"),
"歸"=>array("gwai1"),
"風"=>array("fung1"),
"塵"=>array("can4"),
"三"=>array("saam1"),
"尺"=>array("cek3"),
"劍"=>array("gim3"),
"社"=>array("se5"),
"稷"=>array("zik1"),
"一"=>array("jat1"),
"戎"=>array("jung4"),
"衣"=>array("ji1"),
"翼"=>array("jik6"),
"亮"=>array("loeng6"),
"貞"=>array("zing1"),
"文"=>array("man4"),
"德"=>array("dak1"),
"丕"=>array("pei1"),
"承"=>array("sing4"),
"戢"=>array("cap1"),
"武"=>array("mou5"),
"威"=>array("wai1"),
"聖"=>array("sing3"),
"圖"=>array("tou4"),
"天"=>array("tin1"),
"廣"=>array("gwong2"),
"大"=>array("daai6"),
"宗"=>array("zung1"),
"祀"=>array("zi6"),
"日"=>array("jat6"),
"光"=>array("gwong1"),
"輝"=>array("fai1"),
"陵"=>array("ling4"),
"寢"=>array("cam2"),
"盤"=>array("pun4"),
"空"=>array("hung1"),
"曲"=>array("kuk1"),
"熊"=>array("hung4"),
"羆"=>array("bei1"),
"守"=>array("sau2"),
"翠"=>array("ceoi3"),
"微"=>array("mei4"),
"再"=>array("zoi3"),
"窺"=>array("kwai1"),
"松"=>array("cung4"),
"柏"=>array("paak3"),
"路"=>array("lou6"),
"還"=>array("waan4"),
"見"=>array("gin3"),
"五"=>array("ng5"),
"雲"=>array("wan4"),
"飛"=>array("fei1")
),
"韻部"=>
array(
"〚0199:3.2.5〛"=>"歸：微韻",
"〚0199:4.2.5〛"=>"衣：微韻",
"〚0199:5.2.5〛"=>"威：微韻",
"〚0199:6.2.5〛"=>"輝：微韻",
"〚0199:7.2.5〛"=>"微：微韻",
"〚0199:8.2.5〛"=>"飛：微韻")
,

);
?>