<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《贈翰林張四學士》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"翰林逼華蓋。鯨力破滄溟。"=>array("hon6 lam4 bik1 waa4 goi3, king4 lik6 po3 cong1 ming4","仄平仄平仄，平仄仄平平"),
"天上張公子。宮中漢客星。"=>array("tin1 soeng6 zoeng1 gung1 zi2, gung1 zung1 hon3 haak3 sing1","平仄平平仄，平平仄仄平"),
"賦詩拾翠殿。佐酒望雲亭。"=>array("fu3 si1 sap6 ceoi3 din6, zo3 zau2 mong6 wan4 ting4","仄平仄仄仄，仄仄仄平平"),
"紫誥仍兼綰。黃麻似六經。"=>array("zi2 gou3 jing4 gim1 waan2, wong4 maa4 ci5 luk6 ging1","仄仄平平仄，平平仄仄平"),
"內分金帶赤。恩與荔枝青。"=>array("noi6 fan1 gam1 daai3 cek3, jan1 jyu5 lai6 zi1 cing1","仄平平仄仄，平仄仄平平"),
"無復隨高鳳。空餘泣聚螢。"=>array("mou4 fuk6 ceoi4 gou1 fung6, hung1 jyu4 jap1 zeoi6 jing4","平仄平平仄，平平仄仄平"),
"此生任春草。垂老獨漂萍。"=>array("ci2 sang1 jam6 ceon1 cou2, seoi4 lou5 duk6 piu1 ping4","仄平仄平仄，平仄仄平平"),
"儻憶山陽會。悲歌在一聽。"=>array("tong2 jik1 saan1 joeng4 wui6, bei1 go1 zoi6 jat1 ting1","仄仄平平仄，平平仄仄平"),),
"字音"=>array(
"翰"=>array("hon6"),
"林"=>array("lam4"),
"逼"=>array("bik1"),
"華"=>array("waa4"),
"蓋"=>array("goi3"),
"鯨"=>array("king4"),
"力"=>array("lik6"),
"破"=>array("po3"),
"滄"=>array("cong1"),
"溟"=>array("ming4"),
"天"=>array("tin1"),
"上"=>array("soeng6"),
"張"=>array("zoeng1"),
"公"=>array("gung1"),
"子"=>array("zi2"),
"宮"=>array("gung1"),
"中"=>array("zung1"),
"漢"=>array("hon3"),
"客"=>array("haak3"),
"星"=>array("sing1"),
"賦"=>array("fu3"),
"詩"=>array("si1"),
"拾"=>array("sap6"),
"翠"=>array("ceoi3"),
"殿"=>array("din6"),
"佐"=>array("zo3"),
"酒"=>array("zau2"),
"望"=>array("mong6"),
"雲"=>array("wan4"),
"亭"=>array("ting4"),
"紫"=>array("zi2"),
"誥"=>array("gou3"),
"仍"=>array("jing4"),
"兼"=>array("gim1"),
"綰"=>array("waan2"),
"黃"=>array("wong4"),
"麻"=>array("maa4"),
"似"=>array("ci5"),
"六"=>array("luk6"),
"經"=>array("ging1"),
"內"=>array("noi6"),
"分"=>array("fan1"),
"金"=>array("gam1"),
"帶"=>array("daai3"),
"赤"=>array("cek3"),
"恩"=>array("jan1"),
"與"=>array("jyu5"),
"荔"=>array("lai6"),
"枝"=>array("zi1"),
"青"=>array("cing1"),
"無"=>array("mou4"),
"復"=>array("fuk6"),
"隨"=>array("ceoi4"),
"高"=>array("gou1"),
"鳳"=>array("fung6"),
"空"=>array("hung1"),
"餘"=>array("jyu4"),
"泣"=>array("jap1"),
"聚"=>array("zeoi6"),
"螢"=>array("jing4"),
"此"=>array("ci2"),
"生"=>array("sang1"),
"任"=>array("jam6"),
"春"=>array("ceon1"),
"草"=>array("cou2"),
"垂"=>array("seoi4"),
"老"=>array("lou5"),
"獨"=>array("duk6"),
"漂"=>array("piu1"),
"萍"=>array("ping4"),
"儻"=>array("tong2"),
"憶"=>array("jik1"),
"山"=>array("saan1"),
"陽"=>array("joeng4"),
"會"=>array("wui6"),
"悲"=>array("bei1"),
"歌"=>array("go1"),
"在"=>array("zoi6"),
"一"=>array("jat1"),
"聽"=>array("ting1")
),
"韻部"=>
array(
"〚0204:3.2.5〛"=>"溟：青韻",
"〚0204:4.2.5〛"=>"星：青韻",
"〚0204:5.2.5〛"=>"亭：青韻",
"〚0204:6.2.5〛"=>"經：青韻",
"〚0204:7.2.5〛"=>"青：青韻",
"〚0204:8.2.5〛"=>"螢：青韻",
"〚0204:9.2.5〛"=>"萍：青韻",
"〚0204:10.2.5〛"=>"聽：青韻")
,
"補充説明"=>
"〚3〛首聯對仗。",

);
?>