<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《奉留贈集賢院崔于二學士》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"昭代將垂白。途窮乃叫閽。"=>array("ciu1 doi6 zoeng1 seoi4 baak6, tou4 kung4 naai5 giu3 fan1"),
"氣衝星象表。詞感帝王尊。"=>array("hei3 cung1 sing1 zoeng6 biu2, ci4 gam2 dai3 wong4 zyun1"),
"天老書題目。春官驗討論。"=>array("tin1 lou5 syu1 tai4 muk6, ceon1 gun1 jim6 tou2 leon4"),
"倚風遺鶂路。隨水到龍門。"=>array("ji2 fung1 wai4 jik6 lou6, ceoi4 seoi2 dou3 lung4 mun4"),
"竟與蛟螭雜。寧無燕雀喧。"=>array("ging2 jyu5 gaau1 ci1 zaap6, ning4 mou4 jin3 zoek3 hyun1"),
"青冥猶契闊。陵厲不飛翻。"=>array("cing1 ming4 jau4 kit3 fut3, ling4 lai6 bat1 fei1 faan1"),
"儒術誠難起。家聲庶已存。"=>array("jyu4 seot6 sing4 naan4 hei2, gaa1 seng1 syu3 ji5 cyun4"),
"故山多藥物。勝槪憶桃源。"=>array("gu3 saan1 do1 joek6 mat6, sing3 koi3 jik1 tou4 jyun4"),
"欲整還鄕旆。長懷禁掖垣。"=>array("juk6 zing2 waan4 hoeng1 pui3, coeng4 waai4 gam3 jik6 wun4"),
"謬稱三賦在。難述二公恩。"=>array("mau6 cing1 saam1 fu3 zoi6, naan4 seot6 ji6 gung1 jan1"),),
"字音"=>array(
"昭"=>array("ciu1"),
"代"=>array("doi6"),
"將"=>array("zoeng1"),
"垂"=>array("seoi4"),
"白"=>array("baak6"),
"途"=>array("tou4"),
"窮"=>array("kung4"),
"乃"=>array("naai5"),
"叫"=>array("giu3"),
"閽"=>array("fan1"),
"氣"=>array("hei3"),
"衝"=>array("cung1"),
"星"=>array("sing1"),
"象"=>array("zoeng6"),
"表"=>array("biu2"),
"詞"=>array("ci4"),
"感"=>array("gam2"),
"帝"=>array("dai3"),
"王"=>array("wong4"),
"尊"=>array("zyun1"),
"天"=>array("tin1"),
"老"=>array("lou5"),
"書"=>array("syu1"),
"題"=>array("tai4"),
"目"=>array("muk6"),
"春"=>array("ceon1"),
"官"=>array("gun1"),
"驗"=>array("jim6"),
"討"=>array("tou2"),
"論"=>array("leon4"),
"倚"=>array("ji2"),
"風"=>array("fung1"),
"遺"=>array("wai4"),
"鶂"=>array("jik6"),
"路"=>array("lou6"),
"隨"=>array("ceoi4"),
"水"=>array("seoi2"),
"到"=>array("dou3"),
"龍"=>array("lung4"),
"門"=>array("mun4"),
"竟"=>array("ging2"),
"與"=>array("jyu5"),
"蛟"=>array("gaau1"),
"螭"=>array("ci1"),
"雜"=>array("zaap6"),
"寧"=>array("ning4"),
"無"=>array("mou4"),
"燕"=>array("jin3"),
"雀"=>array("zoek3"),
"喧"=>array("hyun1"),
"青"=>array("cing1"),
"冥"=>array("ming4"),
"猶"=>array("jau4"),
"契"=>array("kit3"),
"闊"=>array("fut3"),
"陵"=>array("ling4"),
"厲"=>array("lai6"),
"不"=>array("bat1"),
"飛"=>array("fei1"),
"翻"=>array("faan1"),
"儒"=>array("jyu4"),
"術"=>array("seot6"),
"誠"=>array("sing4"),
"難"=>array("naan4"),
"起"=>array("hei2"),
"家"=>array("gaa1"),
"聲"=>array("seng1"),
"庶"=>array("syu3"),
"已"=>array("ji5"),
"存"=>array("cyun4"),
"故"=>array("gu3"),
"山"=>array("saan1"),
"多"=>array("do1"),
"藥"=>array("joek6"),
"物"=>array("mat6"),
"勝"=>array("sing3"),
"槪"=>array("koi3"),
"憶"=>array("jik1"),
"桃"=>array("tou4"),
"源"=>array("jyun4"),
"欲"=>array("juk6"),
"整"=>array("zing2"),
"還"=>array("waan4"),
"鄕"=>array("hoeng1"),
"旆"=>array("pui3"),
"長"=>array("coeng4"),
"懷"=>array("waai4"),
"禁"=>array("gam3"),
"掖"=>array("jik6"),
"垣"=>array("wun4"),
"謬"=>array("mau6"),
"稱"=>array("cing1"),
"三"=>array("saam1"),
"賦"=>array("fu3"),
"在"=>array("zoi6"),
"述"=>array("seot6"),
"二"=>array("ji6"),
"公"=>array("gung1"),
"恩"=>array("jan1")
),
"韻部"=>
array(
"〚0288:3.2.5〛"=>"閽：元韻",
"〚0288:4.2.5〛"=>"尊：元韻",
"〚0288:5.2.5〛"=>"論：元韻",
"〚0288:6.2.5〛"=>"門：元韻",
"〚0288:7.2.5〛"=>"喧：元韻",
"〚0288:8.2.5〛"=>"翻：元韻",
"〚0288:9.2.5〛"=>"存：元韻",
"〚0288:10.2.5〛"=>"源：元韻",
"〚0288:11.2.5〛"=>"垣：元韻",
"〚0288:12.2.5〛"=>"恩：元韻")
,

);
?>