<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《敬贈鄭諫議十韻》的資料。
*/
$粵内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"諫官非不達。詩義早知名。"=>array("gaan3 gun1 fei1 bat1 daat6, si1 ji6 zou2 zi1 ming4","仄平平仄仄，平仄仄平平"),
"破的由來事。先鋒孰敢爭。"=>array("po3 dik1 jau4 loi4 si6, sin1 fung1 suk6 gam2 zang1","仄仄平平仄，平平仄仄平"),
"思飄雲物外。律中鬼神驚。"=>array("si1 piu1 wan4 mat6 ngoi6, leot6 zung3 gwai2 san4 ging1","平平平仄仄，仄仄仄平平"),
"毫髮無遺恨。波瀾獨老成。"=>array("hou4 faat3 mou4 wai4 han6, bo1 laan4 duk6 lou5 sing4","仄仄平平仄，平平仄仄平"),
"野人寧得所。天意薄浮生。"=>array("je5 jan4 ning4 dak1 so2, tin1 ji3 bok6 fau4 sang1","仄平平仄仄，平仄仄平平"),
"多病休儒服。冥搜信客旌。"=>array("do1 bing6 jau1 jyu4 fuk6, ming4 sau2 seon3 haak3 zing1","平仄平平仄，平平仄仄平"),
"築居仙縹緲。旅食歲崢嶸。"=>array("zuk1 geoi1 sin1 piu5/piu1 miu5, leoi5 sik6 seoi3 zang1 wing4","仄平平仄仄，平平仄仄平"),
"使者求顏闔。諸公厭禰衡。"=>array("si3 ze2 kau4 ngaan4 hap6, zyu1 gung1 jim3 nei5 hang4","仄仄平平仄，平平仄仄平"),
"將期一諾重。欻使寸心傾。"=>array("zoeng1 kei4 jat1 nok6 zung6, fat1 si2 cyun3 sam1 king1","平平仄仄仄，仄仄仄平平"),
"君見途窮哭。宜憂阮步兵。"=>array("gwan1 gin3 tou4 kung4 huk1, ji4 jau1 jyun2 bou6 bing1","平仄平平仄，平平仄仄平"),),
"字音"=>array(
"諫"=>array("gaan3"),
"官"=>array("gun1"),
"非"=>array("fei1"),
"不"=>array("bat1"),
"達"=>array("daat6"),
"詩"=>array("si1"),
"義"=>array("ji6"),
"早"=>array("zou2"),
"知"=>array("zi1"),
"名"=>array("ming4"),
"破"=>array("po3"),
"的"=>array("dik1"),
"由"=>array("jau4"),
"來"=>array("loi4"),
"事"=>array("si6"),
"先"=>array("sin1"),
"鋒"=>array("fung1"),
"孰"=>array("suk6"),
"敢"=>array("gam2"),
"爭"=>array("zang1"),
"思"=>array("si1"),
"飄"=>array("piu1"),
"雲"=>array("wan4"),
"物"=>array("mat6"),
"外"=>array("ngoi6"),
"律"=>array("leot6"),
"中"=>array("zung3"),
"鬼"=>array("gwai2"),
"神"=>array("san4"),
"驚"=>array("ging1"),
"毫"=>array("hou4"),
"髮"=>array("faat3"),
"無"=>array("mou4"),
"遺"=>array("wai4"),
"恨"=>array("han6"),
"波"=>array("bo1"),
"瀾"=>array("laan4"),
"獨"=>array("duk6"),
"老"=>array("lou5"),
"成"=>array("sing4"),
"野"=>array("je5"),
"人"=>array("jan4"),
"寧"=>array("ning4"),
"得"=>array("dak1"),
"所"=>array("so2"),
"天"=>array("tin1"),
"意"=>array("ji3"),
"薄"=>array("bok6"),
"浮"=>array("fau4"),
"生"=>array("sang1"),
"多"=>array("do1"),
"病"=>array("bing6"),
"休"=>array("jau1"),
"儒"=>array("jyu4"),
"服"=>array("fuk6"),
"冥"=>array("ming4"),
"搜"=>array("sau2"),
"信"=>array("seon3"),
"客"=>array("haak3"),
"旌"=>array("zing1"),
"築"=>array("zuk1"),
"居"=>array("geoi1"),
"仙"=>array("sin1"),
"縹"=>array("piu5","piu1"),
"緲"=>array("miu5"),
"旅"=>array("leoi5"),
"食"=>array("sik6"),
"歲"=>array("seoi3"),
"崢"=>array("zang1"),
"嶸"=>array("wing4"),
"使"=>array("si3","si2"),
"者"=>array("ze2"),
"求"=>array("kau4"),
"顏"=>array("ngaan4"),
"闔"=>array("hap6"),
"諸"=>array("zyu1"),
"公"=>array("gung1"),
"厭"=>array("jim3"),
"禰"=>array("nei5"),
"衡"=>array("hang4"),
"將"=>array("zoeng1"),
"期"=>array("kei4"),
"一"=>array("jat1"),
"諾"=>array("nok6"),
"重"=>array("zung6"),
"欻"=>array("fat1"),
"寸"=>array("cyun3"),
"心"=>array("sam1"),
"傾"=>array("king1"),
"君"=>array("gwan1"),
"見"=>array("gin3"),
"途"=>array("tou4"),
"窮"=>array("kung4"),
"哭"=>array("huk1"),
"宜"=>array("ji4"),
"憂"=>array("jau1"),
"阮"=>array("jyun2"),
"步"=>array("bou6"),
"兵"=>array("bing1")
),
"韻部"=>
array(
"〚0311:3.2.5〛"=>"名：庚韻",
"〚0311:4.2.5〛"=>"爭：庚韻",
"〚0311:5.2.5〛"=>"驚：庚韻",
"〚0311:6.2.5〛"=>"成：庚韻",
"〚0311:7.2.5〛"=>"生：庚韻",
"〚0311:8.2.5〛"=>"旌：庚韻",
"〚0311:9.2.5〛"=>"嶸：庚韻",
"〚0311:10.2.5〛"=>"衡：庚韻",
"〚0311:11.2.5〛"=>"傾：庚韻",
"〚0311:12.2.5〛"=>"兵：庚韻")
,
"補充説明"=>
"〚9.1.4〛縹，上聲。「縹緲」之「縹」讀 piu1，但限於詩律，讀上聲。
〚10.2.4〛禰，上聲。",

);
?>