<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《石硯詩》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"平公今詩伯。秀發吾所羨。"=>array("ping4 gung1 gam1 si1 baak3, sau3 faat3 ng4 so2 sin6"),
"奉使三峽中。長嘯得石硯。"=>array("fung6 si3 saam1 haap6 zung1, coeng4 siu3 dak1 sek6 jin6"),
"巨璞禹鑿餘。異狀君獨見。"=>array("geoi6 pok3 jyu5 zok6 jyu4, ji6 zong6 gwan1 duk6 gin3"),
"其滑乃波濤。其光或雷電。"=>array("kei4 waat6 naai5 bo1 tou4, kei4 gwong1 waak6 leoi4 din6"),
"聯坳各盡墨。多水遞隱見。"=>array("lyun4 aau3 gok3 zeon6 mak6, do1 seoi2 dai6 jan2 jin6"),
"揮灑容數人。十手可對面。"=>array("fai1 saa2 jung4 sou3 jan4, sap6 sau2 ho2 deoi3 min6"),
"比公頭上冠。正質未爲賤。"=>array("bei2 gung1 tau4 soeng6 gun1, zing3 zat1 mei6 wai4 zin6"),
"當公賦佳句。況得終清宴。"=>array("dong1 gung1 fu3 gaai1 geoi3, fong3 dak1 zung1 cing1 jin3"),
"公含起草姿。不遠明光殿。"=>array("gung1 ham4 hei2 cou2 zi1, bat1 jyun5 ming4 gwong1 din6"),
"致于丹青地。知汝隨顧眄。"=>array("zi3 jyu1 daan1 cing1 dei6, zi1 jyu5 ceoi4 gu3 min5"),),
"字音"=>array(
"平"=>array("ping4"),
"公"=>array("gung1"),
"今"=>array("gam1"),
"詩"=>array("si1"),
"伯"=>array("baak3"),
"秀"=>array("sau3"),
"發"=>array("faat3"),
"吾"=>array("ng4"),
"所"=>array("so2"),
"羨"=>array("sin6"),
"奉"=>array("fung6"),
"使"=>array("si3"),
"三"=>array("saam1"),
"峽"=>array("haap6"),
"中"=>array("zung1"),
"長"=>array("coeng4"),
"嘯"=>array("siu3"),
"得"=>array("dak1"),
"石"=>array("sek6"),
"硯"=>array("jin6"),
"巨"=>array("geoi6"),
"璞"=>array("pok3"),
"禹"=>array("jyu5"),
"鑿"=>array("zok6"),
"餘"=>array("jyu4"),
"異"=>array("ji6"),
"狀"=>array("zong6"),
"君"=>array("gwan1"),
"獨"=>array("duk6"),
"見"=>array("gin3","jin6"),
"其"=>array("kei4"),
"滑"=>array("waat6"),
"乃"=>array("naai5"),
"波"=>array("bo1"),
"濤"=>array("tou4"),
"光"=>array("gwong1"),
"或"=>array("waak6"),
"雷"=>array("leoi4"),
"電"=>array("din6"),
"聯"=>array("lyun4"),
"坳"=>array("aau3"),
"各"=>array("gok3"),
"盡"=>array("zeon6"),
"墨"=>array("mak6"),
"多"=>array("do1"),
"水"=>array("seoi2"),
"遞"=>array("dai6"),
"隱"=>array("jan2"),
"揮"=>array("fai1"),
"灑"=>array("saa2"),
"容"=>array("jung4"),
"數"=>array("sou3"),
"人"=>array("jan4"),
"十"=>array("sap6"),
"手"=>array("sau2"),
"可"=>array("ho2"),
"對"=>array("deoi3"),
"面"=>array("min6"),
"比"=>array("bei2"),
"頭"=>array("tau4"),
"上"=>array("soeng6"),
"冠"=>array("gun1"),
"正"=>array("zing3"),
"質"=>array("zat1"),
"未"=>array("mei6"),
"爲"=>array("wai4"),
"賤"=>array("zin6"),
"當"=>array("dong1"),
"賦"=>array("fu3"),
"佳"=>array("gaai1"),
"句"=>array("geoi3"),
"況"=>array("fong3"),
"終"=>array("zung1"),
"清"=>array("cing1"),
"宴"=>array("jin3"),
"含"=>array("ham4"),
"起"=>array("hei2"),
"草"=>array("cou2"),
"姿"=>array("zi1"),
"不"=>array("bat1"),
"遠"=>array("jyun5"),
"明"=>array("ming4"),
"殿"=>array("din6"),
"致"=>array("zi3"),
"于"=>array("jyu1"),
"丹"=>array("daan1"),
"青"=>array("cing1"),
"地"=>array("dei6"),
"知"=>array("zi1"),
"汝"=>array("jyu5"),
"隨"=>array("ceoi4"),
"顧"=>array("gu3"),
"眄"=>array("min5")
),
"韻部"=>
array(
"〚0338:3.2.5〛"=>"羨：霰韻",
"〚0338:4.2.5〛"=>"硯：霰韻",
"〚0338:5.2.5〛"=>"見：霰韻",
"〚0338:6.2.5〛"=>"電：霰韻",
"〚0338:7.2.5〛"=>"見：霰韻",
"〚0338:8.2.5〛"=>"面：霰韻",
"〚0338:9.2.5〛"=>"賤：霰韻",
"〚0338:10.2.5〛"=>"宴：霰韻",
"〚0338:11.2.5〛"=>"殿：霰韻",
"〚0338:12.2.5〛"=>"眄：霰韻")
,
"補充説明"=>
"〚7.2.5〛見，同現。
〚12.2.5〛眄，古上、去聲兩讀。粵音只餘上聲。",

);
?>