<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《城西陂泛舟》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"青蛾皓齒在樓船。橫笛短簫悲遠天。"=>array("cing1 ngo4 hou6 ci2 zoi6 lau4 syun4, waang4 dek6 dyun2 siu1 bei1 jyun5 tin1","平平仄仄仄平平，平仄仄平平仄平"),
"春風自信牙檣動。遲日徐看錦纜牽。"=>array("ceon1 fung1 zi6 seon3 ngaa4 coeng4 dung6, ci4 jat6 ceoi4 hon1 gam2 laam6 hin1","平平仄仄平平仄，平仄平平仄仄平"),
"魚吹細浪搖歌扇。燕蹴飛花落舞筵。"=>array("jyu4 ceoi1 sai3 long6 jiu4 go1 sin3, jin3 cuk1 fei1 faa1 lok6 mou5 jin4","平平仄仄平平仄，仄仄平平仄仄平"),
"不有小舟能盪槳。百壺那送酒如泉。"=>array("bat1 jau5 siu2 zau1 nang4 dong6 zoeng2, baak3 wu4 no4 sung3 zau2 jyu4 cyun4","仄仄仄平平仄仄，仄平平仄仄平平"),),
"字音"=>array(
"青"=>array("cing1"),
"蛾"=>array("ngo4"),
"皓"=>array("hou6"),
"齒"=>array("ci2"),
"在"=>array("zoi6"),
"樓"=>array("lau4"),
"船"=>array("syun4"),
"橫"=>array("waang4"),
"笛"=>array("dek6"),
"短"=>array("dyun2"),
"簫"=>array("siu1"),
"悲"=>array("bei1"),
"遠"=>array("jyun5"),
"天"=>array("tin1"),
"春"=>array("ceon1"),
"風"=>array("fung1"),
"自"=>array("zi6"),
"信"=>array("seon3"),
"牙"=>array("ngaa4"),
"檣"=>array("coeng4"),
"動"=>array("dung6"),
"遲"=>array("ci4"),
"日"=>array("jat6"),
"徐"=>array("ceoi4"),
"看"=>array("hon1"),
"錦"=>array("gam2"),
"纜"=>array("laam6"),
"牽"=>array("hin1"),
"魚"=>array("jyu4"),
"吹"=>array("ceoi1"),
"細"=>array("sai3"),
"浪"=>array("long6"),
"搖"=>array("jiu4"),
"歌"=>array("go1"),
"扇"=>array("sin3"),
"燕"=>array("jin3"),
"蹴"=>array("cuk1"),
"飛"=>array("fei1"),
"花"=>array("faa1"),
"落"=>array("lok6"),
"舞"=>array("mou5"),
"筵"=>array("jin4"),
"不"=>array("bat1"),
"有"=>array("jau5"),
"小"=>array("siu2"),
"舟"=>array("zau1"),
"能"=>array("nang4"),
"盪"=>array("dong6"),
"槳"=>array("zoeng2"),
"百"=>array("baak3"),
"壺"=>array("wu4"),
"那"=>array("no4"),
"送"=>array("sung3"),
"酒"=>array("zau2"),
"如"=>array("jyu4"),
"泉"=>array("cyun4")
),
"韻部"=>
array(
"〚0434:3.1.7〛"=>"船：先韻",
"〚0434:3.2.7〛"=>"天：先韻",
"〚0434:4.2.7〛"=>"牽：先韻",
"〚0434:5.2.7〛"=>"筵：先韻",
"〚0434:6.2.7〛"=>"泉：先韻")
,
"補充説明"=>
"〚6.2.3〛那，平聲。",

);
?>