<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《陪諸貴公子丈八溝攜妓納涼，晚際遇雨二首》的資料。
*/
$粵内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"落日放船好。輕風生浪遲。"=>array("lok6 jat6 fong3 syun4 hou2, hing1 fung1 sang1 long6 ci4","仄仄仄平仄，平平平仄平（「仄平仄」拗，「平仄平」救）"),
"竹深留客處。荷淨納涼時。"=>array("zuk1 sam1 lau4 haak3 cyu3, ho4 zing6 naap6 loeng4 si4","仄平平仄仄，平仄仄平平"),
"公子調冰水。佳人雪藕絲。"=>array("gung1 zi2 tiu4 bing1 seoi2, gaai1 jan4 syut3 ngau5 si1","平仄平平仄，平平仄仄平"),
"片雲頭上黑。應是雨催詩。"=>array("pin3 wan4 tau4 soeng6 hak1, jing1 si6 jyu5 ceoi1 si1","仄平平仄仄，平仄仄平平"),
"雨來霑席上。風急打船頭。"=>array("jyu5 loi4 zim1 zik6 soeng6, fung1 gap1 daa2 syun4 tau4","仄平平仄仄，平仄仄平平"),
"越女紅裙濕。燕姬翠黛愁。"=>array("jyut6 neoi5 hung4 kwan4 sap1, jin1 gei1 ceoi3 doi6 sau4","仄仄平平仄，平平仄仄平"),
"纜侵隄柳繫。幔卷浪花浮。"=>array("laam6 cam1 tai4 lau5 hai6, maan6 gyun2 long6 faa1 fau4","仄平平仄仄，仄仄仄平平"),
"歸路翻蕭颯。陂塘五月秋。"=>array("gwai1 lou6 faan1 siu1 saap3, bei1 tong4 ng5 jyut6 cau1","平仄平平仄，平平仄仄平"),),
"字音"=>array(
"落"=>array("lok6"),
"日"=>array("jat6"),
"放"=>array("fong3"),
"船"=>array("syun4"),
"好"=>array("hou2"),
"輕"=>array("hing1"),
"風"=>array("fung1"),
"生"=>array("sang1"),
"浪"=>array("long6"),
"遲"=>array("ci4"),
"竹"=>array("zuk1"),
"深"=>array("sam1"),
"留"=>array("lau4"),
"客"=>array("haak3"),
"處"=>array("cyu3"),
"荷"=>array("ho4"),
"淨"=>array("zing6"),
"納"=>array("naap6"),
"涼"=>array("loeng4"),
"時"=>array("si4"),
"公"=>array("gung1"),
"子"=>array("zi2"),
"調"=>array("tiu4"),
"冰"=>array("bing1"),
"水"=>array("seoi2"),
"佳"=>array("gaai1"),
"人"=>array("jan4"),
"雪"=>array("syut3"),
"藕"=>array("ngau5"),
"絲"=>array("si1"),
"片"=>array("pin3"),
"雲"=>array("wan4"),
"頭"=>array("tau4"),
"上"=>array("soeng6"),
"黑"=>array("hak1"),
"應"=>array("jing1"),
"是"=>array("si6"),
"雨"=>array("jyu5"),
"催"=>array("ceoi1"),
"詩"=>array("si1"),
"來"=>array("loi4"),
"霑"=>array("zim1"),
"席"=>array("zik6"),
"急"=>array("gap1"),
"打"=>array("daa2"),
"越"=>array("jyut6"),
"女"=>array("neoi5"),
"紅"=>array("hung4"),
"裙"=>array("kwan4"),
"濕"=>array("sap1"),
"燕"=>array("jin1"),
"姬"=>array("gei1"),
"翠"=>array("ceoi3"),
"黛"=>array("doi6"),
"愁"=>array("sau4"),
"纜"=>array("laam6"),
"侵"=>array("cam1"),
"隄"=>array("tai4"),
"柳"=>array("lau5"),
"繫"=>array("hai6"),
"幔"=>array("maan6"),
"卷"=>array("gyun2"),
"花"=>array("faa1"),
"浮"=>array("fau4"),
"歸"=>array("gwai1"),
"路"=>array("lou6"),
"翻"=>array("faan1"),
"蕭"=>array("siu1"),
"颯"=>array("saap3"),
"陂"=>array("bei1"),
"塘"=>array("tong4"),
"五"=>array("ng5"),
"月"=>array("jyut6"),
"秋"=>array("cau1")
),
"韻部"=>
array(
"〚0438:1:5.2.5〛"=>"遲：支韻",
"〚0438:1:6.2.5〛"=>"時：支韻",
"〚0438:1:7.2.5〛"=>"絲：支韻",
"〚0438:1:8.2.5〛"=>"詩：支韻",
"〚0438:2:12.2.5〛"=>"頭：尤韻",
"〚0438:2:13.2.5〛"=>"愁：尤韻",
"〚0438:2:14.2.5〛"=>"浮：尤韻",
"〚0438:2:15.2.5〛"=>"秋：尤韻")
,

);
?>