<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《夏日李公見訪》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"遠林暑氣薄。公子過我遊。"=>array("jyun5 lam4 syu2 hei3 bok6, gung1 zi2 gwo3 ngo5 jau4"),
"貧居類村塢。僻近城南樓。"=>array("pan4 geoi1 leoi6 cyun1 wu2, pik1 gan6 sing4 naam4 lau4"),
"傍舍頗淳朴。所須亦易求。"=>array("pong4 se3 po2 seon4 pok3, so2 seoi1 jik6 ji6 kau4"),
"隔屋喚西家。借問有酒不。"=>array("gaak3 uk1 wun6 sai1 gaa1, ze3 man6 jau5 zau2 fau4"),
"牆頭過濁醪。展席俯長流。"=>array("coeng4 tau4 gwo3 zuk6 lou4, zin2 zik6 fu2 coeng4 lau4"),
"清風左右至。客意已驚秋。"=>array("cing1 fung1 zo2 jau6 zi3, haak3 ji3 ji5 ging1 cau1"),
"巢多眾鳥鬬。葉密鳴蟬稠。"=>array("caau4 do1 zung3 niu5 dau3, jip6 mat6 ming4 sim4 cau4"),
"苦遭此物聒。孰謂吾廬幽。"=>array("fu2 zou1 ci2 mat6 kut3, suk6 wai6 ng4 lou4 jau1"),
"水花晚色靜。庶足充淹留。"=>array("seoi2 faa1 maan5 sik1 zing6, syu3 zuk1 cung1 jim1 lau4"),
"預恐尊中盡。更起爲君謀。（尤韻）"=>array("jyu6 hung2 zoen1 zung1 zeon6, gang3 hei2 wai6 gwan1 mau4"),),
"字音"=>array(
"遠"=>array("jyun5"),
"林"=>array("lam4"),
"暑"=>array("syu2"),
"氣"=>array("hei3"),
"薄"=>array("bok6"),
"公"=>array("gung1"),
"子"=>array("zi2"),
"過"=>array("gwo3"),
"我"=>array("ngo5"),
"遊"=>array("jau4"),
"貧"=>array("pan4"),
"居"=>array("geoi1"),
"類"=>array("leoi6"),
"村"=>array("cyun1"),
"塢"=>array("wu2"),
"僻"=>array("pik1"),
"近"=>array("gan6"),
"城"=>array("sing4"),
"南"=>array("naam4"),
"樓"=>array("lau4"),
"傍"=>array("pong4"),
"舍"=>array("se3"),
"頗"=>array("po2"),
"淳"=>array("seon4"),
"朴"=>array("pok3"),
"所"=>array("so2"),
"須"=>array("seoi1"),
"亦"=>array("jik6"),
"易"=>array("ji6"),
"求"=>array("kau4"),
"隔"=>array("gaak3"),
"屋"=>array("uk1"),
"喚"=>array("wun6"),
"西"=>array("sai1"),
"家"=>array("gaa1"),
"借"=>array("ze3"),
"問"=>array("man6"),
"有"=>array("jau5"),
"酒"=>array("zau2"),
"不"=>array("fau4"),
"牆"=>array("coeng4"),
"頭"=>array("tau4"),
"濁"=>array("zuk6"),
"醪"=>array("lou4"),
"展"=>array("zin2"),
"席"=>array("zik6"),
"俯"=>array("fu2"),
"長"=>array("coeng4"),
"流"=>array("lau4"),
"清"=>array("cing1"),
"風"=>array("fung1"),
"左"=>array("zo2"),
"右"=>array("jau6"),
"至"=>array("zi3"),
"客"=>array("haak3"),
"意"=>array("ji3"),
"已"=>array("ji5"),
"驚"=>array("ging1"),
"秋"=>array("cau1"),
"巢"=>array("caau4"),
"多"=>array("do1"),
"眾"=>array("zung3"),
"鳥"=>array("niu5"),
"鬬"=>array("dau3"),
"葉"=>array("jip6"),
"密"=>array("mat6"),
"鳴"=>array("ming4"),
"蟬"=>array("sim4"),
"稠"=>array("cau4"),
"苦"=>array("fu2"),
"遭"=>array("zou1"),
"此"=>array("ci2"),
"物"=>array("mat6"),
"聒"=>array("kut3"),
"孰"=>array("suk6"),
"謂"=>array("wai6"),
"吾"=>array("ng4"),
"廬"=>array("lou4"),
"幽"=>array("jau1"),
"水"=>array("seoi2"),
"花"=>array("faa1"),
"晚"=>array("maan5"),
"色"=>array("sik1"),
"靜"=>array("zing6"),
"庶"=>array("syu3"),
"足"=>array("zuk1"),
"充"=>array("cung1"),
"淹"=>array("jim1"),
"留"=>array("lau4"),
"預"=>array("jyu6"),
"恐"=>array("hung2"),
"尊"=>array("zoen1"),
"中"=>array("zung1"),
"盡"=>array("zeon6"),
"更"=>array("gang3"),
"起"=>array("hei2"),
"爲"=>array("wai6"),
"君"=>array("gwan1"),
"謀"=>array("mau4"),
"（"=>array(""),
"尤"=>array(""),
"韻"=>array(""),
"）"=>array("")
),
"韻部"=>
"",
"補充説明"=>
"〚6.2.5〛不，平聲。",

);
?>