<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《歎庭前甘菊花》的資料。
*/
$粵内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"簷前甘菊移時晚。青蘂重陽不堪摘。"=>array("jim4 cin4 gam1 guk1 ji4 si4 maan5, cing1 jeoi5 cung4 joeng4 bat1 ham1 zaak6"),
"明日蕭條醉盡醒。殘花爛漫開何益。"=>array("ming4 jat6 siu1 tiu4 zeoi3 zeon6 sing2, caan4 faa1 laan6 maan6 hoi1 ho4 jik1"),
"籬邊野外多眾芳。采擷細瑣升中堂。"=>array("lei4 bin1 je5 ngoi6 do1 zung3 fong1, coi2 kit3 sai3 so2 sing1 zung1 tong4"),
"念茲空長大枝葉。結根失所埋風霜。"=>array("nim6 zi1 hung1 zoeng2 daai6 zi1 jip6, git3 gan1 sat1 so2 maai4 fung1 soeng1"),),
"字音"=>array(
"簷"=>array("jim4"),
"前"=>array("cin4"),
"甘"=>array("gam1"),
"菊"=>array("guk1"),
"移"=>array("ji4"),
"時"=>array("si4"),
"晚"=>array("maan5"),
"青"=>array("cing1"),
"蘂"=>array("jeoi5"),
"重"=>array("cung4"),
"陽"=>array("joeng4"),
"不"=>array("bat1"),
"堪"=>array("ham1"),
"摘"=>array("zaak6"),
"明"=>array("ming4"),
"日"=>array("jat6"),
"蕭"=>array("siu1"),
"條"=>array("tiu4"),
"醉"=>array("zeoi3"),
"盡"=>array("zeon6"),
"醒"=>array("sing2"),
"殘"=>array("caan4"),
"花"=>array("faa1"),
"爛"=>array("laan6"),
"漫"=>array("maan6"),
"開"=>array("hoi1"),
"何"=>array("ho4"),
"益"=>array("jik1"),
"籬"=>array("lei4"),
"邊"=>array("bin1"),
"野"=>array("je5"),
"外"=>array("ngoi6"),
"多"=>array("do1"),
"眾"=>array("zung3"),
"芳"=>array("fong1"),
"采"=>array("coi2"),
"擷"=>array("kit3"),
"細"=>array("sai3"),
"瑣"=>array("so2"),
"升"=>array("sing1"),
"中"=>array("zung1"),
"堂"=>array("tong4"),
"念"=>array("nim6"),
"茲"=>array("zi1"),
"空"=>array("hung1"),
"長"=>array("zoeng2"),
"大"=>array("daai6"),
"枝"=>array("zi1"),
"葉"=>array("jip6"),
"結"=>array("git3"),
"根"=>array("gan1"),
"失"=>array("sat1"),
"所"=>array("so2"),
"埋"=>array("maai4"),
"風"=>array("fung1"),
"霜"=>array("soeng1")
),
"韻部"=>
array(
"〚0490:3.2.7〛"=>"摘，陌韻",
"〚0490:4.2.7〛"=>"益，陌韻",
"〚0490:5.2.7〛"=>"堂，陽韻",
"〚0490:6.2.7〛"=>"霜，陽韻")
,

);
?>