<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《承沈八丈東美除膳部員外，阻雨未遂馳賀，奉寄此詩》的資料。
*/
$粵内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"今日西京掾。多除南省郎。"=>array("gam1 jat6 sai1 ging1 jyun6, do1 ceoi4 naam4 saang2 long4"),
"通家惟沈氏。謁帝似馮唐。"=>array("tung1 gaa1 wai4 sam2 si6, jit3 dai3 ci5 fung4 tong4"),
"詩律羣公問。儒門舊史長。"=>array("si1 leot6 kwan4 gung1 man6, jyu4 mun4 gau6 si2 coeng4"),
"清秋便寓直。列宿頓輝光。"=>array("cing1 cau1 pin4 jyu6 zik6, lit6 sau3 deon6 fai1 gwong1"),
"未暇申宴慰。含情空激揚。"=>array("mei6 haa6 san1 jin3 wai3, ham4 cing4 hung1 gik1 joeng4"),
"司存何所比。膳部默悽傷。"=>array("si1 cyun4 ho4 so2 bei2, sin6 bou6 mak6 cai1 soeng1"),
"貧賤人事略。經過霖潦妨。"=>array("pan4 zin6 jan4 si6 loek6, ging1 gwo3 lam4 lou2 fong4"),
"禮同諸父長。恩豈布衣忘。"=>array("lai5 tung4 zyu1 fu6 zoeng2, jan1 hei2 bou3 ji1 mong4"),
"天路牽騏驥。雲臺引棟梁。"=>array("tin1 lou6 hin1 kei4 kei3, wan4 toi4 jan5 dung6 loeng4"),
"徒懷貢公喜。颯颯鬢毛蒼"=>array("tou4 waai4 gung3 gung1 hei2, saap3 saap3 ban3 mou4 cong1"),),
"字音"=>array(
"今"=>array("gam1"),
"日"=>array("jat6"),
"西"=>array("sai1"),
"京"=>array("ging1"),
"掾"=>array("jyun6"),
"多"=>array("do1"),
"除"=>array("ceoi4"),
"南"=>array("naam4"),
"省"=>array("saang2"),
"郎"=>array("long4"),
"通"=>array("tung1"),
"家"=>array("gaa1"),
"惟"=>array("wai4"),
"沈"=>array("sam2"),
"氏"=>array("si6"),
"謁"=>array("jit3"),
"帝"=>array("dai3"),
"似"=>array("ci5"),
"馮"=>array("fung4"),
"唐"=>array("tong4"),
"詩"=>array("si1"),
"律"=>array("leot6"),
"羣"=>array("kwan4"),
"公"=>array("gung1"),
"問"=>array("man6"),
"儒"=>array("jyu4"),
"門"=>array("mun4"),
"舊"=>array("gau6"),
"史"=>array("si2"),
"長"=>array("coeng4","zoeng2"),
"清"=>array("cing1"),
"秋"=>array("cau1"),
"便"=>array("pin4"),
"寓"=>array("jyu6"),
"直"=>array("zik6"),
"列"=>array("lit6"),
"宿"=>array("sau3"),
"頓"=>array("deon6"),
"輝"=>array("fai1"),
"光"=>array("gwong1"),
"未"=>array("mei6"),
"暇"=>array("haa6"),
"申"=>array("san1"),
"宴"=>array("jin3"),
"慰"=>array("wai3"),
"含"=>array("ham4"),
"情"=>array("cing4"),
"空"=>array("hung1"),
"激"=>array("gik1"),
"揚"=>array("joeng4"),
"司"=>array("si1"),
"存"=>array("cyun4"),
"何"=>array("ho4"),
"所"=>array("so2"),
"比"=>array("bei2"),
"膳"=>array("sin6"),
"部"=>array("bou6"),
"默"=>array("mak6"),
"悽"=>array("cai1"),
"傷"=>array("soeng1"),
"貧"=>array("pan4"),
"賤"=>array("zin6"),
"人"=>array("jan4"),
"事"=>array("si6"),
"略"=>array("loek6"),
"經"=>array("ging1"),
"過"=>array("gwo3"),
"霖"=>array("lam4"),
"潦"=>array("lou2"),
"妨"=>array("fong4"),
"禮"=>array("lai5"),
"同"=>array("tung4"),
"諸"=>array("zyu1"),
"父"=>array("fu6"),
"恩"=>array("jan1"),
"豈"=>array("hei2"),
"布"=>array("bou3"),
"衣"=>array("ji1"),
"忘"=>array("mong4"),
"天"=>array("tin1"),
"路"=>array("lou6"),
"牽"=>array("hin1"),
"騏"=>array("kei4"),
"驥"=>array("kei3"),
"雲"=>array("wan4"),
"臺"=>array("toi4"),
"引"=>array("jan5"),
"棟"=>array("dung6"),
"梁"=>array("loeng4"),
"徒"=>array("tou4"),
"懷"=>array("waai4"),
"貢"=>array("gung3"),
"喜"=>array("hei2"),
"颯"=>array("saap3"),
"鬢"=>array("ban3"),
"毛"=>array("mou4"),
"蒼"=>array("cong1")
),
"韻部"=>
array(
"〚0494:3.2.5〛"=>"郎：陽韻",
"〚0494:4.2.5〛"=>"唐：陽韻",
"〚0494:5.2.5〛"=>"長：陽韻",
"〚0494:6.2.5〛"=>"光：陽韻",
"〚0494:7.2.5〛"=>"揚：陽韻",
"〚0494:8.2.5〛"=>"傷：陽韻",
"〚0494:9.2.5〛"=>"妨：陽韻",
"〚0494:10.2.5〛"=>"忘：陽韻",
"〚0494:11.2.5〛"=>"梁：陽韻",
"〚0494:12.2.5〛"=>"蒼：陽韻")
,

);
?>