<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《示從孫濟》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"平明跨驢出。未知適誰門。"=>array("ping4 ming4 kwaa3 lou4 ceot1, mei6 zi1 sik1 seoi4 mun4"),
"權門多噂𠴲。且復尋諸孫。"=>array("kyun4 mun4 do1 zyun2 daap6, ce2 fuk6 cam4 zyu1 syun1"),
"諸孫貧無事。宅舍如荒村。"=>array("zyu1 syun1 pan4 mou4 si6, zaak6 se3 jyu4 fong1 cyun1"),
"堂前自生竹。堂後自生萱。"=>array("tong4 cin4 zi6 sang1 zuk1, tong4 hau6 zi6 sang1 hyun1"),
"萱草秋已死。竹枝霜不蕃。"=>array("hyun1 cou2 cau1 ji5 sei2, zuk1 zi1 soeng1 bat1 faan4"),
"淘米少汲水。汲多井水渾。"=>array("tou4 mai5 siu2 kap1 seoi2, kap1 do1 zeng2 seoi2 wan4"),
"刈葵莫放手。放手傷葵根。"=>array("ngaai6 kwai4 mok6 fong3 sau2, fong3 sau2 soeng1 kwai4 gan1"),
"阿翁懶惰久。覺兒行步奔。"=>array("aa3 jung1 laan5 do6 gau2, gok3 ji4 hang4 bou6 ban1"),
"所來爲宗族。亦不爲盤飱。"=>array("so2 loi4 wai6 zung1 zuk6, jik6 bat1 wai6 pun4 syun1"),
"小人利口實。薄俗難可論。"=>array("siu2 jan4 lei6 hau2 sat6, bok6 zuk6 naan4 ho2 leon4"),
"勿受外嫌猜。同姓古所敦。"=>array("mat6 sau6 ngoi6 jim4 caai1, tung4 sing3 gu2 so2 deon1"),),
"字音"=>array(
"平"=>array("ping4"),
"明"=>array("ming4"),
"跨"=>array("kwaa3"),
"驢"=>array("lou4"),
"出"=>array("ceot1"),
"未"=>array("mei6"),
"知"=>array("zi1"),
"適"=>array("sik1"),
"誰"=>array("seoi4"),
"門"=>array("mun4"),
"權"=>array("kyun4"),
"多"=>array("do1"),
"噂"=>array("zyun2"),
"𠴲"=>array("daap6"),
"且"=>array("ce2"),
"復"=>array("fuk6"),
"尋"=>array("cam4"),
"諸"=>array("zyu1"),
"孫"=>array("syun1"),
"貧"=>array("pan4"),
"無"=>array("mou4"),
"事"=>array("si6"),
"宅"=>array("zaak6"),
"舍"=>array("se3"),
"如"=>array("jyu4"),
"荒"=>array("fong1"),
"村"=>array("cyun1"),
"堂"=>array("tong4"),
"前"=>array("cin4"),
"自"=>array("zi6"),
"生"=>array("sang1"),
"竹"=>array("zuk1"),
"後"=>array("hau6"),
"萱"=>array("hyun1"),
"草"=>array("cou2"),
"秋"=>array("cau1"),
"已"=>array("ji5"),
"死"=>array("sei2"),
"枝"=>array("zi1"),
"霜"=>array("soeng1"),
"不"=>array("bat1"),
"蕃"=>array("faan4"),
"淘"=>array("tou4"),
"米"=>array("mai5"),
"少"=>array("siu2"),
"汲"=>array("kap1"),
"水"=>array("seoi2"),
"井"=>array("zeng2"),
"渾"=>array("wan4"),
"刈"=>array("ngaai6"),
"葵"=>array("kwai4"),
"莫"=>array("mok6"),
"放"=>array("fong3"),
"手"=>array("sau2"),
"傷"=>array("soeng1"),
"根"=>array("gan1"),
"阿"=>array("aa3"),
"翁"=>array("jung1"),
"懶"=>array("laan5"),
"惰"=>array("do6"),
"久"=>array("gau2"),
"覺"=>array("gok3"),
"兒"=>array("ji4"),
"行"=>array("hang4"),
"步"=>array("bou6"),
"奔"=>array("ban1"),
"所"=>array("so2"),
"來"=>array("loi4"),
"爲"=>array("wai6"),
"宗"=>array("zung1"),
"族"=>array("zuk6"),
"亦"=>array("jik6"),
"盤"=>array("pun4"),
"飱"=>array("syun1"),
"小"=>array("siu2"),
"人"=>array("jan4"),
"利"=>array("lei6"),
"口"=>array("hau2"),
"實"=>array("sat6"),
"薄"=>array("bok6"),
"俗"=>array("zuk6"),
"難"=>array("naan4"),
"可"=>array("ho2"),
"論"=>array("leon4"),
"勿"=>array("mat6"),
"受"=>array("sau6"),
"外"=>array("ngoi6"),
"嫌"=>array("jim4"),
"猜"=>array("caai1"),
"同"=>array("tung4"),
"姓"=>array("sing3"),
"古"=>array("gu2"),
"敦"=>array("deon1")
),
"韻部"=>
array(
"〚0501:3.2.5〛"=>"門：元韻",
"〚0501:4.2.5〛"=>"孫：元韻",
"〚0501:5.2.5〛"=>"村：元韻",
"〚0501:6.2.5〛"=>"萱：元韻",
"〚0501:7.2.5〛"=>"蕃：元韻",
"〚0501:8.2.5〛"=>"渾：元韻",
"〚0501:9.2.5〛"=>"根：元韻",
"〚0501:10.2.5〛"=>"奔：元韻",
"〚0501:11.2.5〛"=>"飱：元韻",
"〚0501:12.2.5〛"=>"論：元韻",
"〚0501:13.2.5〛"=>"敦：元韻")
,

);
?>