<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《贈獻納使起居田舍人》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"獻納司存雨露邊。地分清切任才賢。"=>array("hin3 naap6 si1 cyun4 jyu5 lou6 bin1, dei6 fan1 cing1 cit3 jam6 coi4 jin4","仄仄平平仄仄平，仄平平仄仄平平"),
"舍人退食收封事。宮女開函近御筵。"=>array("se3 jan4 teoi3 sik6 sau1 fung1 si6, gung1 neoi5 hoi1 haam4 gan6 jyu6 jin4","仄平仄仄平平仄，仄仄平平仄仄平"),
"曉漏追趨青瑣闥。晴窗點檢白雲篇。"=>array("hiu2 lau6 zeoi1 ceoi1 cing1 so2 taat3, cing4 coeng1 dim2 gim2 baak6 wan4 pin1","仄仄平平平仄仄，平平仄仄仄平平"),
"揚雄更有河東賦。唯待吹噓送上天。"=>array("joeng4 hung4 gang3 jau5 ho4 dung1 fu3, wai4 doi6 ceoi1 heoi1 sung3 soeng5 tin1","平平仄仄平平仄，平仄平平仄仄平"),),
"字音"=>array(
"獻"=>array("hin3"),
"納"=>array("naap6"),
"司"=>array("si1"),
"存"=>array("cyun4"),
"雨"=>array("jyu5"),
"露"=>array("lou6"),
"邊"=>array("bin1"),
"地"=>array("dei6"),
"分"=>array("fan1"),
"清"=>array("cing1"),
"切"=>array("cit3"),
"任"=>array("jam6"),
"才"=>array("coi4"),
"賢"=>array("jin4"),
"舍"=>array("se3"),
"人"=>array("jan4"),
"退"=>array("teoi3"),
"食"=>array("sik6"),
"收"=>array("sau1"),
"封"=>array("fung1"),
"事"=>array("si6"),
"宮"=>array("gung1"),
"女"=>array("neoi5"),
"開"=>array("hoi1"),
"函"=>array("haam4"),
"近"=>array("gan6"),
"御"=>array("jyu6"),
"筵"=>array("jin4"),
"曉"=>array("hiu2"),
"漏"=>array("lau6"),
"追"=>array("zeoi1"),
"趨"=>array("ceoi1"),
"青"=>array("cing1"),
"瑣"=>array("so2"),
"闥"=>array("taat3"),
"晴"=>array("cing4"),
"窗"=>array("coeng1"),
"點"=>array("dim2"),
"檢"=>array("gim2"),
"白"=>array("baak6"),
"雲"=>array("wan4"),
"篇"=>array("pin1"),
"揚"=>array("joeng4"),
"雄"=>array("hung4"),
"更"=>array("gang3"),
"有"=>array("jau5"),
"河"=>array("ho4"),
"東"=>array("dung1"),
"賦"=>array("fu3"),
"唯"=>array("wai4"),
"待"=>array("doi6"),
"吹"=>array("ceoi1"),
"噓"=>array("heoi1"),
"送"=>array("sung3"),
"上"=>array("soeng5"),
"天"=>array("tin1")
),
"韻部"=>
array(
"〚0536:3.1.7〛"=>"邊：先韻",
"〚0536:3.2.7〛"=>"賢：先韻",
"〚0536:4.2.7〛"=>"筵：先韻",
"〚0536:5.2.7〛"=>"篇：先韻",
"〚0536:6.2.7〛"=>"天：先韻")
,

);
?>