<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《贈田九判官》的資料。
*/
$粵内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"崆峒使節上青霄。河隴降王款聖朝。"=>array("hung1 tung4 si3 zit3 soeng5 cing1 siu1, ho4 lung5 hong4 wong4 fun2 sing3 ziu1","平平仄仄仄平平，平仄平平仄仄平"),
"宛馬總肥春苜蓿。將軍只數漢嫖姚。"=>array("jyun1 maa5 zung2 fei4 ceon1 muk6 suk1, zoeng1 gwan1 zi2 sou2 hon3 biu1 jiu4","平仄仄平平仄仄，平平仄仄仄平平"),
"陳留阮瑀誰爭長。京兆田郎早見招。"=>array("can4 lau4 jyun2 jyu5 seoi4 zang1 zoeng2, ging1 siu6 tin4 long4 zou2 gin3 ziu1","平平仄仄平平仄，平仄平平仄仄平"),
"麾下賴君才幷入。獨能無意向漁樵。"=>array("fai1 haa6 laai6 gwan1 coi4 bing6 jap6, duk6 nang4 mou4 ji3 hoeng3 jyu4 ciu4","平仄仄平平仄仄，仄平仄仄仄平平"),),
"字音"=>array(
"崆"=>array("hung1"),
"峒"=>array("tung4"),
"使"=>array("si3"),
"節"=>array("zit3"),
"上"=>array("soeng5"),
"青"=>array("cing1"),
"霄"=>array("siu1"),
"河"=>array("ho4"),
"隴"=>array("lung5"),
"降"=>array("hong4"),
"王"=>array("wong4"),
"款"=>array("fun2"),
"聖"=>array("sing3"),
"朝"=>array("ziu1"),
"宛"=>array("jyun1"),
"馬"=>array("maa5"),
"總"=>array("zung2"),
"肥"=>array("fei4"),
"春"=>array("ceon1"),
"苜"=>array("muk6"),
"蓿"=>array("suk1"),
"將"=>array("zoeng1"),
"軍"=>array("gwan1"),
"只"=>array("zi2"),
"數"=>array("sou2"),
"漢"=>array("hon3"),
"嫖"=>array("biu1"),
"姚"=>array("jiu4"),
"陳"=>array("can4"),
"留"=>array("lau4"),
"阮"=>array("jyun2"),
"瑀"=>array("jyu5"),
"誰"=>array("seoi4"),
"爭"=>array("zang1"),
"長"=>array("zoeng2"),
"京"=>array("ging1"),
"兆"=>array("siu6"),
"田"=>array("tin4"),
"郎"=>array("long4"),
"早"=>array("zou2"),
"見"=>array("gin3"),
"招"=>array("ziu1"),
"麾"=>array("fai1"),
"下"=>array("haa6"),
"賴"=>array("laai6"),
"君"=>array("gwan1"),
"才"=>array("coi4"),
"幷"=>array("bing6"),
"入"=>array("jap6"),
"獨"=>array("duk6"),
"能"=>array("nang4"),
"無"=>array("mou4"),
"意"=>array("ji3"),
"向"=>array("hoeng3"),
"漁"=>array("jyu4"),
"樵"=>array("ciu4")
),
"韻部"=>
array(
"〚0557:3.1.7〛"=>"霄：蕭韻",
"〚0557:3.2.7〛"=>"朝：蕭韻",
"〚0557:4.2.7〛"=>"姚：蕭韻",
"〚0557:5.2.7〛"=>"招：蕭韻",
"〚0557:6.2.7〛"=>"樵：蕭韻")
,

);
?>