<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《題省中院壁》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"掖垣竹埤梧十尋。洞門對霤常陰陰。"=>array("jik6 wun4 zuk1 pei4 ng4 sap6 cam4, dung6 mun4 deoi3 lau6 soeng4 jam1 jam1","仄平仄平平仄平，仄平仄仄平平平"),
"落花遊絲白日靜。鳴鳩乳燕青春深。"=>array("lok6 faa1 jau4 si1 baak6 jat6 zing6, ming4 gau1 jyu5 jin3 cing1 ceon1 sam1","仄平平平仄仄仄，平平仄仄平平平"),
"腐儒衰晚謬通籍。退食遲迴違寸心。"=>array("fu6 jyu4 seoi1 maan5 mau6 tung1 zik6, teoi3 sik6 ci4 wui4 wai4 cyun3 sam1","仄平平仄平平仄，仄平平平平仄平"),
"衮職曾無一字補。許身愧比雙南金。"=>array("gwan2 zik1 cang4 mou4 jat1 zi6 bou2, heoi2 san1 kwai5 bei2 soeng1 naam4 gam1","仄仄平平仄仄仄，仄平仄仄平平平"),),
"字音"=>array(
"掖"=>array("jik6"),
"垣"=>array("wun4"),
"竹"=>array("zuk1"),
"埤"=>array("pei4"),
"梧"=>array("ng4"),
"十"=>array("sap6"),
"尋"=>array("cam4"),
"洞"=>array("dung6"),
"門"=>array("mun4"),
"對"=>array("deoi3"),
"霤"=>array("lau6"),
"常"=>array("soeng4"),
"陰"=>array("jam1"),
"落"=>array("lok6"),
"花"=>array("faa1"),
"遊"=>array("jau4"),
"絲"=>array("si1"),
"白"=>array("baak6"),
"日"=>array("jat6"),
"靜"=>array("zing6"),
"鳴"=>array("ming4"),
"鳩"=>array("gau1"),
"乳"=>array("jyu5"),
"燕"=>array("jin3"),
"青"=>array("cing1"),
"春"=>array("ceon1"),
"深"=>array("sam1"),
"腐"=>array("fu6"),
"儒"=>array("jyu4"),
"衰"=>array("seoi1"),
"晚"=>array("maan5"),
"謬"=>array("mau6"),
"通"=>array("tung1"),
"籍"=>array("zik6"),
"退"=>array("teoi3"),
"食"=>array("sik6"),
"遲"=>array("ci4"),
"迴"=>array("wui4"),
"違"=>array("wai4"),
"寸"=>array("cyun3"),
"心"=>array("sam1"),
"衮"=>array("gwan2"),
"職"=>array("zik1"),
"曾"=>array("cang4"),
"無"=>array("mou4"),
"一"=>array("jat1"),
"字"=>array("zi6"),
"補"=>array("bou2"),
"許"=>array("heoi2"),
"身"=>array("san1"),
"愧"=>array("kwai5"),
"比"=>array("bei2"),
"雙"=>array("soeng1"),
"南"=>array("naam4"),
"金"=>array("gam1")
),
"韻部"=>
array(
"〚1028:3.1.7〛"=>"尋，侵韻",
"〚1028:3.2.7〛"=>"陰，侵韻",
"〚1028:4.2.7〛"=>"深，侵韻",
"〚1028:5.2.7〛"=>"心，侵韻",
"〚1028:6.2.7〛"=>"金，侵韻")
,
"補充説明"=>
"此詩多拗句。",

);
?>