<?php
/*
生成：本文檔用 PHP 生成。
說明：陳永明《杜甫全集粵音注音》中關於《曲江陪鄭八丈南史飲》的資料。
*/
$内容=array(
"書名"=>"陳永明《杜甫全集粵音注音》",
"注音"=>
array(

"雀啄江頭黃柳花。鵁鶄鸂鶒滿晴沙。"=>array("zoek3 doek3 gong1 tau4 wong4 lau5 faa1, gaau1 zing1 kai1 cik1 mun5 cing4 saa1","仄仄平平平仄平，平平平仄仄平平"),
"自知白髮非春事。且盡芳尊戀物華。"=>array("zi6 zi1 baak6 faat3 fei1 ceon1 si6, ce2 zeon6 fong1 zeon1 lyun2 mat6 waa4","仄平仄仄平平仄，仄仄平平仄仄平"),
"近侍卽今難浪迹。此身那得更無家。"=>array("gan6 si6 zik1 gam1 naan4 long6 zik1, ci2 san1 no4 dak1 gang3 mou4 gaa1","仄仄仄平平仄仄，仄平平仄仄平平"),
"丈人文力猶強健。豈傍青門學種瓜。"=>array("zoeng6 jan4 man4 lik6 jau4 koeng4 gin6, hei2 bong6 cing1 mun4 hok6 zung3 gwaa1","仄平平仄平平仄，仄仄平平仄仄平"),),
"字音"=>array(
"雀"=>array("zoek3"),
"啄"=>array("doek3"),
"江"=>array("gong1"),
"頭"=>array("tau4"),
"黃"=>array("wong4"),
"柳"=>array("lau5"),
"花"=>array("faa1"),
"鵁"=>array("gaau1"),
"鶄"=>array("zing1"),
"鸂"=>array("kai1"),
"鶒"=>array("cik1"),
"滿"=>array("mun5"),
"晴"=>array("cing4"),
"沙"=>array("saa1"),
"自"=>array("zi6"),
"知"=>array("zi1"),
"白"=>array("baak6"),
"髮"=>array("faat3"),
"非"=>array("fei1"),
"春"=>array("ceon1"),
"事"=>array("si6"),
"且"=>array("ce2"),
"盡"=>array("zeon6"),
"芳"=>array("fong1"),
"尊"=>array("zeon1"),
"戀"=>array("lyun2"),
"物"=>array("mat6"),
"華"=>array("waa4"),
"近"=>array("gan6"),
"侍"=>array("si6"),
"卽"=>array("zik1"),
"今"=>array("gam1"),
"難"=>array("naan4"),
"浪"=>array("long6"),
"迹"=>array("zik1"),
"此"=>array("ci2"),
"身"=>array("san1"),
"那"=>array("no4"),
"得"=>array("dak1"),
"更"=>array("gang3"),
"無"=>array("mou4"),
"家"=>array("gaa1"),
"丈"=>array("zoeng6"),
"人"=>array("jan4"),
"文"=>array("man4"),
"力"=>array("lik6"),
"猶"=>array("jau4"),
"強"=>array("koeng4"),
"健"=>array("gin6"),
"豈"=>array("hei2"),
"傍"=>array("bong6"),
"青"=>array("cing1"),
"門"=>array("mun4"),
"學"=>array("hok6"),
"種"=>array("zung3"),
"瓜"=>array("gwaa1")
),
"韻部"=>
array(
"〚1040:3.1.7〛"=>"花，麻韻",
"〚1040:3.2.7〛"=>"沙，麻韻",
"〚1040:4.2.7〛"=>"華，麻韻",
"〚1040:5.2.7〛"=>"家，麻韻",
"〚1040:6.2.7〛"=>"瓜，麻韻")
,
"補充説明"=>
"〚5.2.3〛那，平聲。",

);
?>