<?php

/*
生成：本文檔用 PHP 生成。
程式：生成書本注釋.php
說明：把譯文集中在一個文檔裏。
*/
$Stephen_Owen_The_Poetry_of_Du_Fu譯文=array(
"〚0003:3〛"=>"And what then is Daizong like? — over Qi and Lu, green unending.",
"〚0003:4〛"=>"Creation compacted spirit splendors here, Dark and Light, riving dusk and dawn.",
"〚0003:5〛"=>"Exhilirating the breast, it produces layers of cloud; splitting eye-pupils, it has homing birds entering.",
"〚0003:6〛"=>"Someday may I climb up to its highest summit, with one sweeping view see how small all other mountains are.",
"〚0008:3〛"=>"An eastern province, days of “rushing through the yard,” from its south tower I first let my eyes roam free.",
"〚0008:4〛"=>"Drifting clouds stretch to Mount Tai and the sea, the level moors go off into Qing and Xu.",
"〚0008:5〛"=>"The Qin stele is still there on the lonely cliff, an overgrown wall, ruins of the Lu palace.",
"〚0008:6〛"=>"Ever many thoughts of ancient times, looking out, alone, I hesitate uncertain.",
"〚0013:1:5〛"=>"Without companion in spring mountains I came alone seeking you, the thunk of axes hewing wood, the mountains grew still more secluded.",
"〚0013:1:6〛"=>"In lingering chill on the road by a torrent I passed through ice and snow, with sinking sunlight on Stonegate Mountain, I reached your wooded hill.",
"〚0013:1:7〛"=>"Not coveting, by night I recognized the aura of silver and gold, far from harm, at dawn I looked on the deer roaming.",
"〚0013:1:8〛"=>"Following my whim to the distance, I lose thought of service and
retirement — facing you, it seems you are an empty boat adrift.",
"〚0013:2:12〛"=>"This gentleman meets me from time to time, invited, I stay on impulse late in the day.",
"〚0013:2:13〛"=>"A pool under clearing skies, sturgeon abound, among spring plants the deer cry out.",
"〚0013:2:14〛"=>"He particularly urges Du’s ale on me, for Zhang’s pears do not seek elsewhere.",
"〚0013:2:15〛"=>"Perilous, the mountain road to the village ahead, yet going home drunk, I am always free of worries.",
"〚0022:3〛"=>"The autumn waters are clear and bottomless, the briskness cleanses the hearts of the guests.",
"〚0022:4〛"=>"The administrator follows his free whim, on a saddled horse he went off to find someone.",
"〚0022:5〛"=>"An able clerk meets the “linked pair of jade disks,” this splendid banquet costs a whole silver tael.",
"〚0022:6〛"=>"As the day grows late, the flute playing is good, and under the flood the dragon too hums.",
"〚0042:3〛"=>"I had already visited the temple and went on to stay over in the temple precincts.",
"〚0042:4〛"=>"Shadowy ravines produced piping from empty spaces, the moonlit forests scattered their clear shadows.",
"〚0042:5〛"=>"Constellations’ woof pressed close on Heaven’s towers, lying in the clouds, my clothes were cold.",
"〚0042:6〛"=>"About to be awakened, I heard the dawn bell which brought out in me deep awareness.",
"〚3789:1:5〛"=>"Jade-white dew withers and harms forests of maple trees, on Wu Mountain and in Wu Gorges, the atmosphere, bleak and dreary.",
"〚3789:1:6〛"=>"Between river's margins the waves churn level with sky, wind-driven clouds over passes touching earth in shadow.",
"〚3789:1:7〛"=>"Chrysanthemum clumps twice have bloomed forth tears of another day, a lonely boat tied up once and for all a heart set on its homeland.",
"〚3789:1:8〛"=>"Everywhere clothes for cold weather hasten ruler and blade, walls of White Emperor Castle high, pounding blocks urgent in dusk.",
"〚3789:2:12〛"=>"On Kuizhou's lonely walls setting sunlight slants, then always I trust the North Dipper to lead my gaze to the capital.",
"〚3789:2:13〛"=>"Listening to gibbons I really shed tears at their third cry, accepting my mission I pointlessly follow the eighth-month raft.",
"〚3789:2:14〛"=>"The censer in the ministry with portraits eludes the pillow where I lie, hill towers' white-plastered battlements hide the sad reed pipes.",
"〚3789:2:15〛"=>"Just look there at the moon, in wisteria on the rock, it has already cast its light by sandbars on flowers of the reeds.",
"〚3789:3:19〛"=>"A thousand homes of the mountain town are serene in the glow of dawn; day by day in my river tower I sit in an azure haze.",
"〚3789:3:20〛"=>"Out two nights, the fishermen still drift along; in clear fall skies the swallows keep flying on as ever.",
"〚3789:3:21〛"=>"Kuang Heng advising on policy — deeds and fame both slight. Liu Xiang passing on Classics — heart's goal gone awry.",
"〚3789:3:22〛"=>"The young men I once studied with are now most not of low degree; by Five Barrows their horses are plump and the mantles they wear are light.",
"〚3789:4:26〛"=>"I have heard tell that in Chang'an it's like playing chess, a hundred-year span, the world's troubles, grief beyond enduring.",
"〚3789:4:27〛"=>"Mansions of counts and princes all have new masters, those in civil and army uniforms differ from olden times.",
"〚3789:4:28〛"=>"Straight north past fortified mountains kettledrums are thundering; from wagon and horse on western campaigns winged dispatches rush.",
"〚3789:4:29〛"=>"Fish and dragons grow silent now, autumn rivers grow cold, the life I used to have at home is the longing in my heart.",
"〚3789:5:33〛"=>"Palace towers of Penglai stand facing South Mountain, the metal stalk that catches the dew is high in the Milky Way.",
"〚3789:5:34〛"=>"Gazing west to Onyx Pool the Queen Mother is descending, from the east come purple vapors and fill Han Pass.",
"〚3789:5:35〛"=>"Pheasant tails shift in clouds, palace fans open sunlight circles dragon scales, I see the Emperor's face.",
"〚3789:5:36〛"=>"By the gray river I lay once and woke, alarmed that the year had grown late — how often did I, by the gates' blue rings, take my humble place in dawn court's ranks？",
"〚3789:6:40〛"=>"From the mouth of the Qutang Gorge to the Twisting River's side, thousands of miles of wind-blown fog connect pale autumn.",
"〚3789:6:41〛"=>"Through the walled passage to Calyx Manor the royal aura passed, and into tiny Lotus Park the frontier's sorrows entered.",
"〚3789:6:42〛"=>"Beaded hangings and sculpted pillars surrounded brown swans, from brocade cables and ivory mast rose a white gull.",
"〚3789:6:43〛"=>"The head turns with pity and love for those places of song and the dance: Qin since ancient times has been land of emperors.",
"〚3789:7:47〛"=>"The waters of Kunming Pool are a deed of the days of Han, pennons and banners of Emperor Wu are right before my eyes.",
"〚3789:7:48〛"=>"Loom threads of the Weaver Woman lie empty in the moonlit night, stone Leviathan's fins and scales stir the autumn wind.",
"〚3789:7:49〛"=>"Waves toss wild grass seed sinking in cloudy black, dew is chill on the lotus pod shedding powdery red.",
"〚3789:7:50〛"=>"Fortified passes stretch to the skies, a way for only birds, lakes and rivers fill the earth, and one old man, fishing.",
"〚3789:8:54〛"=>"At Kunwu Hill the Yusu Brook winds around and away, where the shadow of Purple Tower's crest falls into Lake Meipi.",
"〚3789:8:55〛"=>"Sweet-smelling rice, pecked the last, for parrots, the grains; sapphire tung trees, perch of old, the phoenix's branches.",
"〚3789:8:56〛"=>"Fair maidens gathered kingfisher plumes, as gentle gifts in spring, sharing a boat, undying companions moved further on that evening.",
"〚3789:8:57〛"=>"My colored brush in former outings ventured upon the atmosphere, now white-haired, I sing and gaze, head hanging in bitterness.",
);
?>